# Generated by Django 4.2.2 on 2023-06-23 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitioWeb',
            fields=[
                ('sitio_web_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('feed_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('publicacion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('imagen_portada', models.CharField(max_length=255)),
                ('extracto', models.CharField(max_length=250)),
                ('sitio_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analis.sitioweb')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reacciones', models.IntegerField()),
                ('comentarios', models.IntegerField()),
                ('veces_compartidas', models.IntegerField()),
                ('comentarios_sitios_web', models.IntegerField()),
                ('total_engagement', models.IntegerField()),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analis.publicacion')),
            ],
        ),
    ]
