# Generated by Django 4.2.6 on 2023-12-19 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0002_publicacion_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloGenerado',
            fields=[
                ('articulo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contenido_generado', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analis.publicacion')),
            ],
        ),
    ]
