# Generated by Django 4.2.6 on 2023-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0003_articulogenerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulogenerado',
            name='nombre_sitio_web',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articulogenerado',
            name='post_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articulogenerado',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='articulogenerado',
            name='url_sitio_web',
            field=models.CharField(default='', max_length=255),
        ),
    ]
