# Generated by Django 4.2.6 on 2023-12-19 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0004_articulogenerado_nombre_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulogenerado',
            name='publicacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analis.publicacion'),
        ),
    ]
