# Generated by Django 4.2.6 on 2023-12-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analis', '0005_alter_articulogenerado_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulogenerado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='fecha_creacion',
        ),
    ]
